bank/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
# from two_factor.urls import urlpatterns as tf_urls
from .views import *
urlpatterns = [
    # path("", include(tf_urls)),
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('about',about, name="about"),
    path('services',services, name="services"),
    path('faq',faq, name="faq"),
    path('terms',terms, name="terms"),
    path('contact',contact, name="contact"),
    path('sign_in',sign_in, name="sign_in"),
    path('sign_up',sign_up, name="sign_up"),
    path('logout',user_logout, name="logout"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('otp', otp_view, name='otp'),
    path('forget_password',forgetpassword, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'),
    path('resetpassword', resetpassword, name='resetpassword'),
    path('account/', include('account.urls')),
    path('', include('core.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'core'

urlpatterns = [
    path('deposit', views.deposit, name='deposit'),
    path('withdrawal', views.withdrawal, name='withdrawal'),
    path('transfer', views.transfer, name='transfer'),
    path('confirm_transfer',views.confirm_transfer, name="confirm_transfer"),
    path('transactions',views.transactions, name='transactions'),
    path('transaction_detail/<int:trn_id>/', views.transaction_detail, name='transaction_detail'),
    path('generate_transaction_statement/', views.TransactionStatementPDF.as_view(), name='generate_transaction_statement'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    path('referral', views.referral, name="referral"),
    path('loan', views.loan_request, name="loan_request"),
    path('chart_support_list', views.chart_support_list, name="chart_support_list"),
    path('chart_support/<int:pk>/', views.chart_support, name="chart_support"),
    path('ajax_load_messages/<int:pk>/', views.ajax_load_messages, name='ajax_load_messages'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/dashboard/partial/_depositAction.html
<div class="modal fade action-sheet" id="depositActionSheet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="border-radius:10px;">
            <div class="modal-header">
                <h5 class="modal-title">Add Balance</h5>
            </div>
            <div class="modal-body">
                <div class="action-sheet-content">
                    <form>
                        <div class="form-group basic">
                            <div class="input-wrapper">
                                <label class="label" for="account1">From</label>
                                <select class="form-control custom-select" id="account1">
                                    <option value="0">Savings (*** 5019)</option>
                                    <option value="1">Investment (*** 6212)</option>
                                    <option value="2">Mortgage (*** 5021)</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addona1">$</span>
                                <input type="text" class="form-control" placeholder="Enter an amount"
                                    value="100">
                            </div>
                        </div>


                        <div class="form-group basic">
                            <button type="button" class="btn btn-primary btn-block btn-lg"
                                data-bs-dismiss="modal">Deposit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/partial/_fundAction.html
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" 
crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<div class="modal fade action-sheet" id="fundActionSheet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="border-radius:10px;">
            <div class="modal-header">
                <h5 class="modal-title">Fund Wallet</h5>
            </div>
            <div class="modal-body">
                <div class="action-sheet-content">
                    

                        <div class="form-group basic">
                            <div class="input-wrapper">
                               
                                <div class="text-center fs-12 mt-4 mb-4">
              
                                    <img class="text-center" src="{% static 'download.png' %}" height="200px" width="200px" alt="">
                                    <h4 class="text-center text-primary fs-12 mt-4">Wallet QR Code</h4>
                                
                                  </div>
                            </div>
                        </div>

                        <form  method="POST" action="{% url 'core:deposit' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group basic">
                                    <div class="input-wrapper">
                                        <label class="label" for="account2">Crypto</label>
                                <select name="crypto" required="required" class="form-control custom-select" onchange="myC()" id="crypto">
                                    <option value="" selected disabled>Select Crypto</option>
                                      <option  value="Bitcoin">Bitcoin</option>
                                      <option  value="Ethereum">Ethereum</option>
                                      <option  value="USDT">USDT</option>
                                </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group basic">
                                    <div class="input-wrapper">
                                        <label class="label" for="currency2">Wallet Address</label>
                                        <input name="wallet_id" type="text" class="form-control input-lg" id="wallet-address" required
                                        value="" readonly>
                                        <button class="btn btn-primary clipboard-icon clipboard-box"
                                                data-clipboard-target="#wallet-address"  onclick="myFunction()" title="">COPY
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                       
                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addon1">$</span>
                                <input required='required' name='amount' type="number" class="form-control" placeholder="Enter an amount"
                                    min="100">
                            </div>
                        </div>
                        <div class="form-group basic">
                            <div class="input-wrapper">
                                <label class="label" for="text11">Transaction ID</label>
                                <input required='required' name='trn_id' type="text" class="form-control" id="text11"
                                    placeholder="Enter Transaction ID">
                               
                            </div>
                        </div>
                        <div class="form-group basic">
                            <div class="input-wrapper">
                                <label class="label" for="text11">Transaction Proof</label>
                                <input type="file" class="form-control" id="text11d" name="trn_proof" required='required'> 
                               
                            </div>
                        </div>


                        <div class="form-group basic">
                            <button type="submit" class="btn btn-primary btn-block btn-lg"
                            onclick="return confirm('Are you sure you want to proceed?')" >Send</button>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function myFunction() {
    /* Get the text field */
    var content = document.getElementById('wallet-address');

content.select();
document.execCommand('copy');

alert("Copied!");
}
  </script>    
  
  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
    function myC() {
      var x = document.getElementById("crypto").value;
      if(x =="Bitcoin"){
        document.getElementById("wallet-address").value = 'bc1qzgwqt2zwlf';
      }else if(x =="Ethereum"){
        document.getElementById("wallet-address").value = '0xEADbD65864D74bF9';
      }else if(x =="USDT"){
        document.getElementById("wallet-address").value = "0x708C5771e1AF5Daf9574F";
      }

    }
    </script>
    

templates/dashboard/partial/_globaltransferAction.html
<div class="modal fade action-sheet" id="globalexchangeActionSheet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="border-radius:10px;">
            <div class="modal-header">
                <h5 class="modal-title">Global Transfer</h5>
            </div>
            <div class="modal-body">
                <div class="action-sheet-content">
                    <p>Coming Soon</p>
                    {% comment %} <form>
                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addon2">$</span>
                                <input type="text" class="form-control" placeholder="Enter an amount"
                                    value="100">
                            </div>
                        </div>
                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addon2">$</span>
                                <input type="text" class="form-control" placeholder="Enter an amount"
                                    value="100">
                            </div>
                        </div>

                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addon2">$</span>
                                <input type="text" class="form-control" placeholder="Enter an amount"
                                    value="100">
                            </div>
                        </div>



                        <div class="form-group basic">
                            <button type="button" class="btn btn-primary btn-block btn-lg"
                                data-bs-dismiss="modal">Exchange</button>
                        </div>
                    </form> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/partial/_localtransferAction.html
<div class="modal fade action-sheet" id="exchangeActionSheet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="border-radius:10px;">
            <div class="modal-header">
                <h5 class="modal-title">Transfer Money</h5>
            </div>
            <div class="modal-body">
                <div class="action-sheet-content">
                    <form method="POST" action="{% url 'core:transfer' %}">
                    {% csrf_token %}
                        <div class="form-group basic">
                            <label class="label">From</label>
                            <div class="input-group mb-2">

                                <input type="text" class="form-control"readonly
                                    value="{{request.user.email}}" required='required'>
                                        
                            </div>
                        </div>
                        <div class="form-group basic">
                            <div class="input-wrapper">
                                <label class="label" for="text11d">PIN</label>
                                <input type="text" name='pin' class="form-control" id="text11d" required='required' placeholder="Enter PIN" oninput="sanitizeInput()" style="color: transparent; background-color: white;">
                                
                            </div>
                        </div>

                        <div class="form-group basic">
                            <label class="label">To</label>
                            <div class="input-group mb-2">
                             
                                <input required='required'type="text" name="recipient_identifier" class="form-control" required='required' placeholder="Enter Account Email">
                            </div>
                        </div>
                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addon2">$</span>
                                <input required='required' name="amount"  type="number" step="0.01" min="100.00" max="100000000000.00"class="form-control" placeholder="Enter an amount">
                            </div>
                        </div>
                        <div class="form-group basic">
                            <label class="label">Description</label>
                            <div class="input-group mb-2">
                            
                                <textarea class="form-control" placeholder="Optional"></textarea>
                                
                            </div>
                        </div>


                        <div class="form-group basic">
                            <button type="submit" class="btn btn-primary btn-block btn-lg"
                            >Send</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/partial/_withdrawAction.html
{% comment %} {% include 'dashboard/alert.html' %} {% endcomment %}

<div class="modal fade action-sheet" id="withdrawActionSheet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="border-radius:10px;">
            <div class="modal-header">
                <h5 class="modal-title">Withdraw Money</h5>
            </div>
            <div class="modal-body">
                <div class="action-sheet-content">
                    <form method="POST" action="{% url 'core:withdrawal' %}">
                        {% csrf_token %}
                        <div class="form-group basic">
                            <div class="input-wrapper">
                                <label class="label" for="text11d">PIN</label>
                                <input type="text" name='pin' class="form-control" id="text11d" required='required' placeholder="Enter PIN" style="color: transparent; background-color: white;">
                                
                            </div>
                        </div>

                        <div class="form-group basic">
                            <label class="label">Enter Amount</label>
                            <div class="input-group mb-2">
                                <span class="input-group-text" id="basic-addonb1">$</span>
                                <input type="number" name='amount' class="form-control" placeholder="Enter an amount"
                                min="100.00" max="100000000000.00" required='required'>
                            </div>
                        </div>

                        <div class="form-group basic">
                            <button type="submit" class="btn btn-primary btn-block btn-lg"
                                onclick="return confirm('Are you sure you want to proceed?')">Withdraw</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>