account/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'account'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('settings', views.settings, name='settings'),
    path('profile_details',views.profile_details, name="profile_details"),
    path('kyc', views.kyc, name='kyc'),
    path('change_password',views.change_password,name='change_password'),
    path('set_pin', views.set_pin, name="set_pin"),
    path('change_pin', views.change_pin, name="change_pin"),
    path('notifications/mark_as_read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications',views.all_notifications, name="all_notifications"),
    # path('load_more_notification', views.load_more_notification, name='load_more_notification'),
    path('two_step_verification', views.two_step_verification, name='two_step_verification'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bank/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
# from two_factor.urls import urlpatterns as tf_urls
from .views import *
urlpatterns = [
    # path("", include(tf_urls)),
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('about',about, name="about"),
    path('services',services, name="services"),
    path('faq',faq, name="faq"),
    path('terms',terms, name="terms"),
    path('contact',contact, name="contact"),
    path('sign_in',sign_in, name="sign_in"),
    path('sign_up',sign_up, name="sign_up"),
    path('logout',user_logout, name="logout"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('otp', otp_view, name='otp'),
    path('forget_password',forgetpassword, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'),
    path('resetpassword', resetpassword, name='resetpassword'),
    path('account/', include('account.urls')),
    path('', include('core.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'core'

urlpatterns = [
    path('deposit', views.deposit, name='deposit'),
    path('withdrawal', views.withdrawal, name='withdrawal'),
    path('transfer', views.transfer, name='transfer'),
    path('confirm_transfer',views.confirm_transfer, name="confirm_transfer"),
    path('transactions',views.transactions, name='transactions'),
    path('transaction_detail/<int:trn_id>/', views.transaction_detail, name='transaction_detail'),
    path('generate_transaction_statement/', views.TransactionStatementPDF.as_view(), name='generate_transaction_statement'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    path('referral', views.referral, name="referral"),
    path('loan', views.loan_request, name="loan_request"),
    path('chart_support_list', views.chart_support_list, name="chart_support_list"),
    path('chart_support/<int:pk>/', views.chart_support, name="chart_support"),
    path('ajax_load_messages/<int:pk>/', views.ajax_load_messages, name='ajax_load_messages'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/dashboard/app-sms-verification.html
<!doctype html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>Finapp</title>
    <meta name="description" content="Finapp HTML Mobile Template">
    <meta name="keywords" content="bootstrap, wallet, banking, fintech mobile template, cordova, phonegap, mobile, html, responsive" />
    <link rel="icon" type="image/png" href="assets/img/favicon.png" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/img/icon/192x192.png">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="manifest" href="__manifest.json">
</head>

<body>

    <!-- loader -->
    <div id="loader">
        <img src="assets/img/loading-icon.png" alt="icon" class="loading-icon">
    </div>
    <!-- * loader -->

    <!-- App Header -->
    <div class="appHeader no-border transparent position-absolute">
        <div class="left">
            <a href="#" class="headerButton goBack">
                <ion-icon name="chevron-back-outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle"></div>
        <div class="right">
        </div>
    </div>
    <!-- * App Header -->

    <!-- App Capsule -->
    <div id="appCapsule">

        <div class="section mt-2 text-center">
            <h1>Enter SMS Code</h1>
            <h4>Enter 4 digit sms verification code</h4>
        </div>
        <div class="section mb-5 p-2">
            <form action="index.html">
                <div class="form-group basic">
                    <input type="text" class="form-control verification-input" id="smscode" placeholder="••••"
                        maxlength="4">
                </div>

                <div class="form-button-group transparent">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Verify</button>
                </div>

            </form>
        </div>

    </div>
    <!-- * App Capsule -->


    <!-- ========= JS Files =========  -->
    <!-- Bootstrap -->
    <script src="assets/js/lib/bootstrap.bundle.min.js"></script>
    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- Splide -->
    <script src="assets/js/plugins/splide/splide.min.js"></script>
    <!-- Base Js File -->
    <script src="assets/js/base.js"></script>


</body>

</html>

templates/dashboard/app-transaction-detail.html
<!doctype html>
{% load static %}
{% load humanize %}
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>CompanyName | Notifications</title>
    <meta name="description" content="Finapp HTML Mobile Template">
    <meta name="keywords"
        content="bootstrap, wallet, banking, fintech mobile template, cordova, phonegap, mobile, html, responsive" />
    <link rel="icon" type="image/png" href="{% static 'dashboard/assets/img/favicon.png' %}" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'dashboard/assets/img/icon/192x192.png' %}">
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<style>
    .not-visible {
        display: none;
    }
</style>

<body class="bg-white">



    <!-- App Header -->
    <div class="appHeader">
        <div class="left">
            <a href="{% url 'core:transactions' %}" class="headerButton goBack">
                <ion-icon name="chevron-back-outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle">
            Transactions
        </div>
        
    </div>
    <!-- * App Header -->


    <!-- App Capsule -->
    <div id="appCapsule" class="full-height">

        <div class="section mt-2 mb-2">

            
            <div class="listed-detail mt-3">
                <div class="icon-wrapper">
                    <div class="iconbox">
                        <ion-icon name="arrow-forward-outline"></ion-icon>
                    </div>
                </div>
                {% if transaction.transaction_type == 'Payment' %}
                <h3 class="text-center mt-2">Payment Sent</h3>
                {% endif %}
                {% if transaction.transaction_type == 'Bill' %}
                <h3 class="text-center mt-2">Bill Payment</h3>
                {% endif %}
            </div>

            <ul class="listview flush transparent simple-listview no-space mt-3">
                {% comment %} <li>
                    <strong>Status</strong>
                    <span class="text-success">Success</span>
                </li> {% endcomment %}
                {% if transaction.recipient.full_name %}
                <li>
                    <strong>To</strong>
                    <span>{{transaction.recipient.full_name}}</span>
                </li>
                {% endif %}
                {% if transaction.recipient.email %}
                <li>
                    <strong>Email</strong>
                    <span>{{transaction.recipient.email}}</span>
                </li>
                {% endif %}
                
                {% if transaction.amount %}
                <li>
                    <strong>Amount</strong>
                    <h3 class="m-0" style="color:red;">-${{transaction.amount}}</h3>
                </li>
                {% endif %}
                {% if transaction.transaction_type %}
                <li>
                    <strong>Transaction Type</strong>
                    <span>{{transaction.transaction_type}}</span>
                </li>
                {% endif %}
                {% if transaction.transaction_id %}
                <li>
                    <strong>Transaction ID</strong>
                    <span>{{transaction.transaction_id}}</span>
                </li> 
                {% endif %}
                {% if transaction.description %}
                <li>
                    <strong>Transaction Description</strong>
                    <span>{{transaction.description}}</span>
                </li> 
                {% endif %}
                {% if transaction.created_at %}
                <li>
                    <strong>Date</strong>
                    <span>{{transaction.created_at}}</span>
                </li>
                {% endif %}
            </ul>

            <a href="/generate_pdf/?transaction_id={{ transaction.transaction_id }}"  class="mt-2 btn btn-primary btn-block btn-lg" data-transaction-id="{{ transaction.transaction_id }}">
            Download Receipt</a>
            
        </div>

    </div>
    <!-- * App Capsule -->

    
    <!-- App Bottom Menu -->
    {% include 'dashboard/app-button-menu.html' %}
    <!-- * App Bottom Menu -->

    <script src="{% static 'dashboard/assets/js/lib/bootstrap.bundle.min.js' %}"></script>
    <!-- Ionicons -->
    {% comment %} <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script> {% endcomment %}
    <!-- Splide -->
    <script src="{% static 'dashboard/assets/js/plugins/splide/splide.min.js' %}"></script>
    <!-- Base Js File -->
    {% comment %} <script src="{% static 'dashboard/assets/js/base.js' %}"></script> {% endcomment %}
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ionicons/7.1.2/esm/ionicons.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/dashboard/app-transactions.html
<!doctype html>
{% load static %}
{% load humanize %}
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>CompanyName | Transactions</title>
    <meta name="description" content="Finapp HTML Mobile Template">
    <meta name="keywords"
        content="bootstrap, wallet, banking, fintech mobile template, cordova, phonegap, mobile, html, responsive" />
    <link rel="icon" type="image/png" href="{% static 'dashboard/assets/img/favicon.png' %}" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'dashboard/assets/img/icon/192x192.png' %}">
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>
<style>
    .not-visible {
        display: none;
    }
</style>

<body class="bg-white">



    <!-- App Header -->
    <div class="appHeader">
        <div class="left">
            <a href="{% url 'account:dashboard' %}" class="headerButton goBack">
                <ion-icon name="chevron-back-outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle">
            Transactions
        </div>
        
    </div>
    <!-- * App Header -->




    <!-- App Capsule -->
    <div id="appCapsule">

        <!-- Transactions -->
        {% if grouped_transactions %}
        {% for date, transactions in grouped_transactions.items %}
        <div class="section mt-2">
            <div class="section-title">{{ date }}</div>
            <div class="transactions">
                {% for transaction in transactions %}
                <!-- item -->
                <a href="{% url 'core:transaction_detail' transaction.id %}" class="item">
                    <div class="detail">
                        {% comment %} <img src="{% if transaction.recipient.profile_picture %}{{transaction.recipient.profile_picture}}{% endif %}" alt="img" class="image-block imaged w48"> {% endcomment %}
                        <div>
                            <strong>{{transaction.recipient.full_name}}</strong>
                            <p>{{ transaction.transaction_type }}</p>
                        </div>
                    </div>
                    <div class="right">
                        <div class="price text-danger">-${{ transaction.amount }}</div>
                    </div>
                </a>
                <!-- * item -->
                <!-- item -->
                
                <!-- * item -->
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        {% else %}
            <div class="container-fluid">
                <p>No Transactions made</p>
            </div>
            {% endif %}
        <!-- * Transactions -->

        {% comment %} <div class="section mt-2 mb-2">
            <a href="#" class="btn btn-primary btn-block btn-lg">Load More</a>
        </div> {% endcomment %}


    </div>
    <!-- * App Capsule -->



    <!-- App Bottom Menu -->
    {% include 'dashboard/app-button-menu.html' %}
    <!-- * App Bottom Menu -->

    <script src="{% static 'dashboard/assets/js/lib/bootstrap.bundle.min.js' %}"></script>
    <!-- Ionicons -->
    {% comment %} <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script> {% endcomment %}
    <!-- Splide -->
    <script src="{% static 'dashboard/assets/js/plugins/splide/splide.min.js' %}"></script>
    <!-- Base Js File -->
    {% comment %} <script src="{% static 'dashboard/assets/js/base.js' %}"></script> {% endcomment %}
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ionicons/7.1.2/esm/ionicons.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/dashboard/chart_support_list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}

    <!-- App Capsule -->
    <div id="appCapsule">
        <div class="section mt-3 text-center">
            <div class="avatar-section">
                <h1>Chart with a support</h1>
            </div>
           
        </div>
        <div class="section mt-2">
            <div class="section-title">Supports</div>
            <div class="card">
                <ul class="listview flush transparent no-line image-listview detailed-list mt-1 mb-1">
                    {% if request.user.is_superuser %}
                        {% if users %}
                            {% for user in users %}
                            
                            <li>
                                <div class="item">
                                    
                                    <div class="in">
                                        <div><a href="{% url 'core:chart_support' user.id %}">
                                            <strong>{{user.full_name}}</strong>
                                            </a>
                                        </div>
                                        <div class="text-end">
                                            
                                            <div class="text-small">
                                                <span class="badge badge-success">
                                                    <ion-icon name="arrow-up-outline"></ion-icon>
                                                    online
                                                </span>
                                                Unread Messages: {{ user.unread_count }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                           
                            {% endfor %}
                        {% endif %}
                    {% else %}
                    
                    {% if adms %}
                    
                    
                    <li>
                        <div class="item">
                            
                            <div class="in">
                                <div><a href="{% url 'core:chart_support' adms.id %}">
                                    <strong>Chat</strong>
                                    </a>
                                </div>
                                <div class="text-end">
                                    
                                    <div class="text-small">
                                        <span class="badge badge-success">
                                            <ion-icon name="arrow-up-outline"></ion-icon>
                                            online
                                        </span>
                                        {% if adms.unread_count %} {{ adms.unread_count }}{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                   
                    {% endif %}
                    {% endif %}
                    
                  
                    <!-- * item -->
                </ul>
            </div>
        </div>
        <!-- Top Coins -->

       

    </div>
    <!-- * App Capsule -->

    
{% endblock %}

templates/dashboard/component-badge.html
<!doctype html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>Finapp</title>
    <meta name="description" content="Finapp HTML Mobile Template">
    <meta name="keywords" content="bootstrap, wallet, banking, fintech mobile template, cordova, phonegap, mobile, html, responsive" />
    <link rel="icon" type="image/png" href="assets/img/favicon.png" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/img/icon/192x192.png">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="manifest" href="__manifest.json">
</head>

<body>

    <!-- loader -->
    <div id="loader">
        <img src="assets/img/loading-icon.png" alt="icon" class="loading-icon">
    </div>
    <!-- * loader -->

    <!-- App Header -->
    <div class="appHeader">
        <div class="left">
            <a href="#" class="headerButton goBack">
                <ion-icon name="chevron-back-outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle">Badges</div>
        <div class="right">
            <a href="#" class="headerButton">
                <ion-icon name="notifications-outline"></ion-icon>
                <span class="badge badge-danger">5</span>
            </a>
        </div>
    </div>
    <!-- * App Header -->

    <!-- App Capsule -->
    <div id="appCapsule" class="full-height">


        <div class="section mt-2">
            <div class="section-title">Colors</div>
            <div class="card">
                <div class="card-body">
                    <span class="badge badge-primary">Primary</span>
                    <span class="badge badge-secondary">Secondary</span>
                    <span class="badge badge-success">Success</span>
                    <div class="mb-05"></div>
                    <span class="badge badge-danger">Danger</span>
                    <span class="badge badge-warning">Warning</span>
                    <span class="badge badge-info">Info</span>
                    <div class="mb-05"></div>
                    <span class="badge badge-light">Light</span>
                    <span class="badge badge-dark">Dark</span>

                    <div class="mt-3"></div>
                    <h4 class="mb-05">Empty Badges</h4>
                    <span class="badge badge-primary badge-empty"></span>
                    <span class="badge badge-secondary badge-empty"></span>
                    <span class="badge badge-success badge-empty"></span>
                    <span class="badge badge-danger badge-empty"></span>
                    <span class="badge badge-warning badge-empty"></span>
                    <span class="badge badge-info badge-empty"></span>
                    <span class="badge badge-dark badge-empty"></span>
                    <span class="badge badge-light badge-empty"></span>
                </div>
            </div>
        </div>


        <div class="section mt-2">
            <div class="section-title">Listview Example</div>
            <div class="card">
                <ul class="listview image-listview transparent flush">
                    <li>
                        <div class="item">
                            <img src="assets/img/sample/avatar/avatar1.jpg" alt="image" class="image">
                            <div class="in">
                                <div>Henry Richardson</div>
                                <span class="badge badge-primary">6</span>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="item">
                            <img src="assets/img/sample/avatar/avatar4.jpg" alt="image" class="image">
                            <div class="in">
                                <div>Diane Lansdowne</div>
                                <span class="badge badge-secondary">NEW</span>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="item">
                            <img src="assets/img/sample/avatar/avatar3.jpg" alt="image" class="image">
                            <div class="in">
                                <div>Lucas Simoes</div>
                                <span class="badge badge-success">86</span>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>



    </div>
    <!-- * App Capsule -->

    <!-- App Bottom Menu -->
    <div class="appBottomMenu">
        <a href="app-components.html" class="item">
            <div class="col">
                <ion-icon name="wallet-outline"></ion-icon>
                <strong>Item 1</strong>
                <span class="badge badge-primary">6</span>
            </div>
        </a>
        <a href="app-components.html" class="item">
            <div class="col">
                <ion-icon name="cash-outline"></ion-icon>
                <strong>Item 2</strong>
                <span class="badge badge-success">52</span>
            </div>
        </a>
        <a href="app-components.html" class="item">
            <div class="col">
                <ion-icon name="earth-outline"></ion-icon>
                <strong>Item 3</strong>
                <span class="badge badge-danger">52</span>
            </div>
        </a>
        <a href="app-components.html" class="item">
            <div class="col">
                <ion-icon name="qr-code-outline"></ion-icon>
                <strong>Item 4</strong>
                <span class="badge badge-warning">8</span>
            </div>
        </a>
        <a href="app-components.html" class="item">
            <div class="col">
                <ion-icon name="notifications-outline"></ion-icon>
                <strong>Item 5</strong>
                <span class="badge badge-info">5</span>
            </div>
        </a>
    </div>
    <!-- * App Bottom Menu -->


    <!-- ========= JS Files =========  -->
    <!-- Bootstrap -->
    <script src="assets/js/lib/bootstrap.bundle.min.js"></script>
    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- Splide -->
    <script src="assets/js/plugins/splide/splide.min.js"></script>
    <!-- Base Js File -->
    <script src="assets/js/base.js"></script>


</body>

</html>

templates/dashboard/transaction_statement_template.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #f5f5f5;
        }

        .money-in {
            color: green;
        }

        .money-out {
            color: red;
        }
    </style>
    <title>Transaction Statement</title>
</head>
<body>
    <div style="text-align:center;">
        <h1>Transaction Statement</h1>
        <p>
            <strong>Names:</strong> {{ user.full_name }}<br>
            <strong>Email:</strong> {{ user.email }}<br>
            <strong>Transactions from:</strong> {{ start_date|date:"F j, Y" }}<br>
            <strong>Transactions to:</strong> {{ end_date|date:"F j, Y" }}
        </p>
    </div>
    <table border="1">
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Sender</th>
                <th>Recipient</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.created_at|date:"F j, Y" }}</td>
                {% if transaction.description == 'False' %}
                <td>Null</td>
                {% else %}
                <td>{{ transaction.description }}</td>
                {% endif %}
                <td>{{ transaction.sender.full_name }}</td>
                <td>{{ transaction.recipient.full_name }}</td>
                <td>{{ transaction.amount }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>